### ISSUE TITLE
Make separate folder for skills

### ISSUE THREAD

**Issue by GlassSpirit** [Sponge-RPG-dev/NT-RPG#104]
Skills-Definition.conf file gets difficult to maintain with a lot of skills, so they could be moved to "skills" folder with .conf file for each skill

**Comment by NeumimTo** [comment]
Theres no skill folder, it would fit inside current addons folder where other skillpacks may be present as .jar libraries already.

**Comment by NeumimTo** [comment]
- Skill packs as .jar libraries are loaded from .deployed folder 
  - These packs are during server startup copied from directory addons to directory .deployed and from there are loaded. 
  - (This is due to planned reloading of .jar libraries at runtime. Java Class Loader keeps the file locked for writing)

- Skill packs as .conf files are loaded from addons folder. 
  - Skills created from these .conf files all share the same class instance of loader.  
  - They are possible to reload via /nadmin reload js

**Comment by GlassSpirit** [comment]
So every Skill.conf file should contain

Skills: [
  {
    id: "someskill"
    ...
  }
]

?

**Comment by NeumimTo** [comment]
Yes, if you want to have one skill per one config file put `Skills: [{...}]` into each .conf file.

If you happen to need to share some common code such as a common js function between two different skills create a file with .js extension inside folder scripts and put it there. 

All scripts share one instance of Nashorn engine this includes same bindings, same context..
